1.2.1-148/Dockerfile
1.2.1-148/main.sh
1.2.1-148/setup.sh
README.md

Adding new version of Linux Agent for ACS

---

1.3.4-127a/setup.sh

Adding omsagent v1.3.4-127 and docker-provider 1.0.0-24

---

1.3.4-127a/setup.sh

Reverting fwlinks and using actual urls instead

---

1.3.4-127a/main.sh

Removing bash verbose and adding onboarding check

---

1.3.4-127a/Dockerfile

Updating docker-provider version to 25

---

Alpine/Dockerfile
Alpine/main.sh
Alpine/setup.sh
Kubernetes/omsagent.yaml

Fixed whitespaces and updated provider version

---

1.4.0-12/Dockerfile
1.4.0-12/main.sh
1.4.0-12/setup.sh
rc/Dockerfile
rc/main.sh
rc/setup.sh

Adding omsagent v1.4.0-12 and rc folder for testing candidate release

Adding omsagent v1.4.0-12 and rc folder for release testing 

---

Kubernetes/k8s-README.md
README.md
ReleaseNote.md
Swarmmode/README.md

Update release note and Readme

---

Kubernetes/omsagent.yaml

Updating agent version in kubernetes deployment yaml file to 1.4.0-12
@keikhara please review and approve

Update agent version to 1.4.0-12

---

OpenShift/README.md
OpenShift/ocp-ds-omsagent.yaml
OpenShift/ocp-omsagent.yaml
OpenShift/ocp-secret-template.yaml
OpenShift/ocp-secretgen.sh

ocp configuration update

---

README.md
ReleaseNote.md

@samisms  updated release note and readme

new release note and readme for next release

---

Kubernetes/README.md
Kubernetes/windows/README.md
Kubernetes/windows/secret-gen.sh
Kubernetes/windows/secret-template.yaml
Kubernetes/windows/ws-omsagent-de-secrets.yaml
README.md
ReleaseNote.md

@samisms Can you please review the following docs? 
thanks, 
Keiko

Updated docs for Windows Kubernetes

---

1.4.1-45/Dockerfile
1.4.1-45/main.sh
1.4.1-45/setup.sh

@keikhara please review and approve.

Add release 1.4.1-45 and docker-provider 1.0.0-28

---

1.4.1-123/Dockerfile
1.4.1-123/main.sh
1.4.1-123/setup.sh

@amitsara 
Added the new dsc added omsagent. Please check and sign-off.

update dsc fix

---

1.4.1-123/Dockerfile
1.4.1-123/main.sh

@keikhara please review and approve

Adding 1.4.1-123 release

---

ReleaseNote.md

Updated bug fixes for the linux agent on the release note.

rel note update for 1.0.0-30

---

1.4.4-210/Dockerfile
1.4.4-210/main.sh
1.4.4-210/setup.sh

@amitsara  
updated the oms linux agent to 1.4.4.-210.  Please check and approve.

1.4.4-210 agent updated

---

ci_feature/main.sh

Add agent telemetry for
* Agent Tag
* Kube version

Agent telemetry

---

ci_feature_prod/Dockerfile
ci_feature_prod/main.sh
ci_feature_prod/setup.sh

added folder for ci_feature_prod

adding ci_feature_prod

---

ci_feature_prod/setup.sh

@Microsoft/docker-provider-devs

Updating oms agent to v1.6.0-23 release

---

.gitignore
Kubernetes/omsagent-ds-secrets.yaml
Kubernetes/omsagent.yaml
ci_feature_prod/Dockerfile
ci_feature_prod/main.sh
ci_feature_prod/setup.sh

Merging from ci_feature_prod to ci_feature (picking up last release) - From next time, we would have to do other way *before/for* every release

Ci feature prod

---

ci_feature/main.sh

Updating URL_TLD for INT workspace onboarding

Passing in domain as parameter

---

docs/solution-onboarding.md
docs/templates/azuremonitor-containerSolutionParams.json

fixing the solution template and docs

solution template fixes

---

docs/solution-onboarding.md
docs/templates/azuremonitor-containerSolutionParams.json

solution template fixes (#161)

---

ci_feature/Dockerfile
ci_feature_prod/Dockerfile

Adding environment variable for agent version

adding environment variable

---

README.md
SUPPORTABILITY.md
Troubleshoot/README.md

This PR following changes and this PR will be merged to newly created aks-engine branch
- README.md file with following details( Product Info,Support Matrix,  Setup and Troubleshooting etc.)
- SUPPORTABILITY.md . This placeholder and needs to be updated either before or after meeting with the support team
- TROUBLESHOOTING.md file with the troubleshooting instructions.
- LICENSE and CONTRIBUTION same as on the master branch

aks-engine-public-preview-doc-updates

---

Kubernetes/omsagent.yaml

updating config map for fixed type

updating config map for fixed type

---

Kubernetes/omsagent.yaml
ci_feature/setup.sh

Update oms agent to the newer version

Update oms agent to latest version

---

Kubernetes/omsagent.yaml

1. Fix multiline configmap formatting.
2. Update agent version
3. Remove liveness probe for setfacl

omsgent yaml update for ci_feature

---

1.8.1-256/Dockerfile
1.8.1-256/main.sh
1.8.1-256/setup.sh
Kubernetes/omsagent.yaml

updating oms agent to use the latest version 1.8.1-256

updating oms agent to use the latest version 1.8.1-256

---

Kubernetes/omsagent.yaml

Updating container node inventory to use fixed type

changes for container node inventory fixed type

---

docs/add-monitoring-metrics-publisher-role.md
docs/aks/mdmonboarding/mdm_onboarding.ps1
docs/aks/mdmonboarding/mdm_onboarding.sh
docs/aks/mdmonboarding/mdm_onboarding_atscale.ps1
docs/aks/mdmonboarding/mdm_onboarding_atscale.sh

This PR contains following changes 
-  Bash and PS scripts for  Monitoring Metrics Publisher role assignment for single  or all the aks clusters in specified subscription
-  Instructions how to onboard the role assignment with Az CLI or PS

scripts and docs for mdm onboarding

---

ci_feature/setup.sh
ci_feature_prod/setup.sh

Update docker provider link to github release

Update docker provider link to github release

---

Kubernetes/omsagent.yaml
ci_feature/acrdevnamespace.yaml
ci_feature/main.sh

* remove k-s log collectin setting
* update hostname for telemetry purposes in rs

merge Vishwa/june19agentrel to ci_feature

---

Troubleshoot/README.md
Troubleshoot/TroubleshootError_AcsEngine.ps1

update the download ps scripts links to use raw and also update the acs-engine script to use aks-engine naming wherever applicable

update the links of script to use raw

---

Troubleshoot/TroubleshootError.ps1

In case you're interested, I needed to make these changes so I could run it from cloud shell / mac

Make troubleshooting script work on non windows

---

docs/hybrid/onboarding_azuremonitor_for_containers.ps1

improve error and warning messages

bug fixes related error and warning messages

---

docs/hybrid/onboarding_azuremonitor_for_containers.ps1

fix weird spacing issue

---

Kubernetes/omsagent-ai-res-id.yaml

Changes to pick up the latest omsagent.yaml changes for omsagent-ai-res-id.yaml

changes to get the latest omsagent yaml

---

Troubleshoot/README.md

Cherry picking this PR: https://github.com/microsoft/OMS-docker/pull/307

Add instruction to download Solution file (#307)

---

docs/haiku/onboarding_azuremonitor_for_containers.ps1

Fix the issue related to attaching tags and also remove --name parameter for helm install command so that it will work with helm3

fix the bug in tag attach

---

docs/aro/disable_monitoring/OptOutParam.json
docs/aro/disable_monitoring/OptOutTemplate.json
docs/aro/enable_monitoring_to_existing_cluster/existingClusterOnboarding.json
docs/aro/enable_monitoring_to_existing_cluster/existingClusterParam.json
docs/aro/enable_monitoring_to_new_cluster/newClusterWithMonitoring.json
docs/aro/enable_monitoring_to_new_cluster/newClusterWithMonitoringParam.json

ARM templates related to onboarding and offboarding ARO clusters (existing and new) to monitoring.

arm templates related onboarding and offboarding aro to monitoring

---

Troubleshoot/TroubleshootError_nonAzureK8s.ps1

troubelshooting script for non azure k8s clusters

troubelshoot script for non azure k8s clusters

---

Kubernetes/omsagent.yaml

Use node affinity instead of node selector for replicaset to not schedule it on master nodes

Use node affinity for replicaset

---

Kubernetes/omsagent.yaml

Removing node affinity for replicaset, since we dont have dependency on the agent node anymore.

Remove node affinity for replicaset

---

ci_feature/main.sh
ci_feature_prod/main.sh

Update blob url to ifconfig

---

Troubleshoot/README.md
Troubleshoot/TroubleshootError.ps1
Troubleshoot/TroubleshootError_nonAzureK8s.ps1

This PR has following updates ...
1. update the script updates to troubleshoot the issues related to ARO onboarding
2. update the script issue related to agent side issues 
3. detect the workspace daily cap and throw an error if the usage is equal or over the configured cap limits
4. suppress the warnings related to cmdlets
5. update the doc updates

Update Troubleshoot script to catch the agent side issues and ARO onboarding

---

docs/haiku/onboarding_azuremonitor_for_containers.ps1

script updates to for azure arc cluster private preview onboarding

update onboarding script for azure arc cluster

---

Kubernetes/omsagent.yaml

Yaml changes to be consistent with aks rp yaml

Yaml changes to be consistent with aks rp yaml 

---

Troubleshoot/TroubleshootError_nonAzureK8s.ps1

script updates for secure port and labels etc

script updates for secure port and labels etc

---

Kubernetes/container-azm-ms-agentconfig.yaml
Kubernetes/omsagent.yaml
ci_feature/main.sh
ci_feature_prod/main.sh

MSI changes, network connectivity, kubevents configmap

MSI changes, network connectivity, kubevents configmap

---

docs/openshiftV4/onboarding_azuremonitor_for_containers.sh

use upgrade --install to install or upgrade chart

use upgrade --install to install or upgrade chart

---

Kubernetes/omsagent.yaml
ci_feature/Dockerfile
ci_feature/setup.sh
ci_feature_prod/Dockerfile
ci_feature_prod/setup.sh

changes for ciprod04162020 release
- yaml 
- docker file
- setup file change with update to docker provider version and  docker provider 9.0.0-1 release url

changes for ciprod04162020 release

---

Troubleshoot/TroubleshootError.ps1

fix the error when cluster and ws in different subs

fix the error when cluster and ws in different subs

---

Kubernetes/windows/scripts/powershell/main.ps1
ci_feature/main.sh
ci_feature_prod/main.sh

This PR is enables proxy support for the agent  so that  Linux and Windows agent can be used behind proxy environment.
For external outbound traffic, OMS, ODS, AI, MDM  and on-boarding check communications will be routed via Proxy if Proxy configured.
Refer latest design doc https://microsoft.sharepoint.com/:w:/t/Operations_Management_Suite/EWITL1uDq6BPpgv8taRppd4BxKE5H9st5AgRT8nLIAiZsA?e=fIwOVV

Gangams/enable proxy support (for non-AKS) remote endpoints

---

Kubernetes/omsagent.yaml
Kubernetes/windows/Dockerfile
Kubernetes/windows/acrWorkflows/acrcreate.ps1
Kubernetes/windows/fluent/fluent.conf
Kubernetes/windows/scripts/powershell/main.ps1
ci_feature/Dockerfile
ci_feature/setup.sh
ci_feature_prod/Dockerfile
ci_feature_prod/setup.sh

merge ci_feature to ci_feature_prod for ciprod05262020 release

merge ci_feature to ci_feature_prod for ciprod05262020 release

---

Kubernetes/omsagent.yaml

yaml update for ciprod05262020

yaml update for ciprod05262020

---

docs/haiku/onboarding_azuremonitor_for_containers.sh

fix arc onboarding issue

---

Kubernetes/omsagent.yaml

-> Merged #417 into ci_feature.
-> Created branch bragi92/cherry_pick_yaml_windwos_tag from 'ci_feature_prod'
-> Cherry picked 35a75ffe2054388540f9102d1527bb9e7fc4d0eb aka the commit from ci_feature into this branch (bragi92/cherry_pick_yaml_windows_tag)
-> Created PR to merge this into ci_feature_prod to maintain the commit history.

Cherry-Pick : Update windows image tag in yaml (#417)

---

1.14.12-0/Dockerfile
1.14.12-0/main.sh
1.14.12-0/setup.sh
Kubernetes/omsagent.yaml

Updating omsagent to version 1.14.12
Updating docker-cimprov to version 1.0.0-40

Update omsagent and docker-cimprov versions
